"""Increase source_name length

Revision ID: 228c8c594478
Revises: 334a9fa76dd8
Create Date: 2026-07-31 22:42:53.398506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228c8c594478'
down_revision = '334a9fa76dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_source', schema=None) as batch_op:
        batch_op.alter_column('source_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_source', schema=None) as batch_op:
        batch_op.alter_column('source_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
